# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20160902_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'Start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpage',
            name='date_to',
            field=models.DateField(blank=True, help_text=b'Not required if event is on a single day', null=True, verbose_name=b'End date'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='leaders',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='participants',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Number of participants'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Start time'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name=b'End time'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='audience',
            field=models.CharField(choices=[(b'otwarte', b'Otwarte'), (b'klubowe', b'Klubowe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='cost',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
