# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20170311_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Godzina poczatku'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Godzina konca'),
        ),
    ]
