# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20170311_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(verbose_name=b'Data sporzadzenia relacji'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date_from',
            field=models.DateField(verbose_name=b'Data poczatku wydarzenia'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date_to',
            field=models.DateField(blank=True, help_text=b'Nie wymagane, jesli wydarzenie jednodniowe', null=True, verbose_name=b'Data konca wydarzenia'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='leaders',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Przewodnik, osoby organizujace'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Miejsce wydarzenia'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='participants',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Ilosc uczestnikow'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='audience',
            field=models.CharField(choices=[(b'otwarte', b'Otwarte'), (b'klubowe', b'Klubowe')], max_length=255, verbose_name=b'Zakres wydarzenia'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='cost',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Koszty wyjazdu'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateField(verbose_name=b'Data poczatku wydarzenia'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date_to',
            field=models.DateField(blank=True, help_text=b'Nie wymagane, jesli wydarzenie jednodniowe', null=True, verbose_name=b'Data konca wydarzenia'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='location',
            field=models.CharField(max_length=255, verbose_name=b'Miejsce wydarzenia'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='signup_link',
            field=models.URLField(blank=True, verbose_name=b'Link do formularza zapisowego'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Godzina poczatku'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Godzina konca'),
        ),
    ]
